### PR TITLE
fix estonian version

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Llewellynvdm** [comment]
I am sorry for the delay, but I ca not find any one to confirm that this update is correct. Can you please get someone who also understand and know Estonian to verify this fix.

Or can you give me a link to a reputable Bible website that has this translation in it, to verify the text.

Forgive me for being so protective, but I am sure you understand.

**Comment by ibex-of-entropy** [comment]
I know and understand estonian, also I checked it multiple times at different positions, estonian bible versions [here](http://dev.piibel.net/ebook/), also you can see that your version has most texts missing

**Comment by Llewellynvdm** [comment]
You do not understand, I do not know you. Don't take this personal... but there is no way I can know that you are not breaking the scripture and twisting it. So I need to validate the changes from another source then you.

I got this version, with all the missing verses, from a reputable source. So before I can allow it to be fixed I need to insure that it is still the original text.

Okay I will evaluate the text based on the http://dev.piibel.net/ebook/ and get back to you.

**Comment by ibex-of-entropy** [comment]
yes of course, would you also like the extractor I built to convert the epub to your format?

**Comment by Llewellynvdm** [comment]
Sure let me see if I can make use of it.

**Comment by Llewellynvdm** [comment]
@ibex-of-entropy I am still waiting for the extractor you used... but the delay has been completely my fault. Hope you can forgive me.

At last we have Estonian translation updated. I am working on adding a json version of all the translations to this repo, well in fact I am basically going to do this per/translation and then per/book and per/chapter and per/verse so that the github repo can serve as the DB to fetch text.

I am building the converter in bash using jq templates. At last I get to work on what I love....!

**Pull request merged**
